-- schema_onboarding.sql
-- Add onboarding columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS student_type VARCHAR(20) CHECK (student_type IN ('college','competitive','self_learner'));
ALTER TABLE users ADD COLUMN IF NOT EXISTS college_name VARCHAR(150);
ALTER TABLE users ADD COLUMN IF NOT EXISTS degree VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS study_year VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS branch VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS exam_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS exam_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS learning_topic VARCHAR(150);
ALTER TABLE users ADD COLUMN IF NOT EXISTS learning_goal VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS learning_reason VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_minutes INT DEFAULT 60;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_onboarded BOOLEAN DEFAULT FALSE;

-- Create subjects table
CREATE TABLE IF NOT EXISTS subjects (
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    color VARCHAR(7) DEFAULT '#7C3AED',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
